---
name: default

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # python
      - uses: actions/setup-python@v3
        with:
          cache: poetry

      # pre-commit
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pip install pre-commit

      # poetry
      - run: pip install poetry
      - run: poetry install

      # target
      - run: make check

      # sanity check
      - run: git diff --exit-code
        if: ${{ !env.ACT }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # python
      - uses: actions/setup-python@v3
        with:
          cache: poetry

      # poetry
      - run: pip install poetry
      - run: poetry install

      # target
      - run: make install
      - run: make test

      # sanity check
      - run: git diff --exit-code
        if: ${{ !env.ACT }}
